### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by Mastertomspirit** [SanJSp/lets_git_exercise_de#44]
There´s a spelling mistake in [Readme](https://github.com/SanJSp/lets_git_exercise_de/blob/master/README.md) at line 12:

>Request ein Passwort für das Quiz auf openHPI kommentieren. `Das sollst dann für die entsprechende Aufgabe eingeben.`

Better:

>Request ein Passwort für das Quiz auf openHPI kommentieren. Das sollst <span style="color:red">**`du`**</span> dann für die entsprechende Aufgabe eingeben. 

:eyes:

Wenns aber als Slang durchgeht, dann is der issue halt ne Zusatzübung.. 

:+1:   :laughing:

**Comment by SanJSp** [comment]
Hi @Mastertomspirit , kannst du dafür vielleicht einen Pull Request erstellen? Das wäre super und würde dir ein wenig Übung geben 😄 

Liebe Grüße   
Sandro
